name: Maven Build
on:
  schedule:
    - cron: '30 0 * 3/9 MON'
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
env:
  TEST: KEY
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            17
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  another-job:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'mac-os']
        variant: ['sdkman']
        include:
    permissions:
      actions: read
      checks: write
      contents: none
    steps:
      - name: step-0
        if: ${{ always() }}
        run: |
          less test.txt
          echo 1