---
name: 'test-WF'
jobs:
  update-concourse-tasks:
    name: 'update-concourse-tasks'
    cancel-timeout-minutes: 5
    concurrency:
      group: 'grp'
      cancel-in-progress: true
    container:
      ports:
        - 80
        - 90
      volumes:
        - '/etc:~/test'
        - '/opt:~/test'
      image: 'alpine'
      options: '--cpu 1'
      credentials:
        username: 'user'
        password: '1234'
      env:
        h: 'v'
    environment: 'NonProd'
    runs-on: 'self-hosted'
    continue-on-error: true
    defaults:
      run:
        shell: 'bash'
        working-directory: '.'
    env:
      key: 'value'
      key2: 'value2'
    if: '${{ condition }}'
on:
  schedule:
    - cron: '* * * * *'
    - cron: '1 * * * *'
    - cron: '2 * * * *'
  check_suite:
    types:
      - 'completed'
  check_run:
    types:
      - 'completed'
      - 'created'
  workflow_dispatch:
    outputs:
      version:
        value: '1.0.0'
    inputs:
      in:
        description: 'totoootot'
        type: 'boolean'
        default: 'false'
        required: true
      test:
        options:
          - 'lol'
          - 'foo'
  push:
    branches:
      - 'master'
    branches-ignore:
      - 'not_master'
    tags:
      - 'my_tag'
    tags-ignore:
      - 'not_my_tag'
    paths:
      - '/path1'
      - '/path 2'
    paths-ignore:
      - 'test/path'
  registry_package:
    types:
      - 'published'
